SET foreign_key_checks = 0;
DROP DATABASE IF EXISTS CONTACT_INFO_MASTER;
CREATE DATABASE CONTACT_INFO_MASTER;

GRANT ALL PRIVILEGES
ON CONTACT_INFO_MASTER.*
TO 'villageworks'@'localhost'
IDENTIFIED BY 'vw78works'
WITH GRANT OPTION;

GRANT ALL PRIVILEGES
ON CONTACT_INFO_MASTER.*
TO 'villageworks'@'%'
IDENTIFIED BY 'vw78works'
WITH GRANT OPTION;

USE CONTACT_INFO_MASTER;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_LANGUAGE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_LANGUAGE` (
    ID INT NOT NULL AUTO_INCREMENT,
    LANGUAGE_ID INT UNIQUE NOT NULL,
    LANGUAGE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_COUNTRY`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_COUNTRY` (
    ID INT NOT NULL AUTO_INCREMENT,
    COUNTRY_ID VARCHAR(30) UNIQUE NOT NULL,
    COUNTRY_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_DISTRICT_USER_CLASSIFICATION`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_DISTRICT_USER_CLASSIFICATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_CLASSIFICATION_ID INT UNIQUE NOT NULL,
    USER_CLASSIFICATION_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_TEACHER_CLASSIFICATION`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_TEACHER_CLASSIFICATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    TEACHER_CLASSIFICATION_ID INT UNIQUE NOT NULL,
    TEACHER_CLASSIFICATION_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_PHONE_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_PHONE_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    PHONE_TYPE_ID INT UNIQUE NOT NULL,
    PHONE_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_EMAIL_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_EMAIL_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL_TYPE_ID INT UNIQUE NOT NULL,
    EMAIL_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_RACE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_RACE` (
    ID INT NOT NULL AUTO_INCREMENT,
    RACE_ID INT UNIQUE NOT NULL,
    RACE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ADDRESS_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ADDRESS_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    ADDRESS_TYPE_ID INT UNIQUE NOT NULL,
    ADDRESS_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STATE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STATE` (
    ID INT NOT NULL AUTO_INCREMENT,
    STATE_ID INT UNIQUE NOT NULL,
    STATE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_GENDER`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_GENDER` (
    ID INT NOT NULL AUTO_INCREMENT,
    GENDER_ID INT UNIQUE NOT NULL,
    GENDER_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_PERSONAL_VERIFICATION_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_PERSONAL_VERIFICATION_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    PERSONAL_VERIFICATION_TYPE_ID INT UNIQUE NOT NULL,
    PERSONAL_VERIFICATION_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_RELATION`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_RELATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    RELATION_ID INT UNIQUE NOT NULL,
    RELATION_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STUDENT_ID_SYSTEM_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STUDENT_ID_SYSTEM_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_ID_SYSTEM_TYPE_ID INT UNIQUE NOT NULL,
    STUDENT_ID_SYSTEM_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STUDENT_STATUS`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STUDENT_STATUS` (
    ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_STATUS_ID INT UNIQUE NOT NULL,
    STUDENT_STATUS_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_OTHERNAME_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_OTHERNAME_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    OTHERNAME_TYPE_ID INT UNIQUE NOT NULL,
    OTHERNAME_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STUDENT_CHARACTERISTICS`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_STUDENT_CHARACTERISTICS` (
    ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_CHARACTERISTICS_ID  INT UNIQUE NOT NULL,
    STUDENT_CHARACTERISTICS_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_COHORT_YEAR`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_COHORT_YEAR` (
    ID INT NOT NULL AUTO_INCREMENT,
    COHORT_YEAR_ID INT UNIQUE NOT NULL,
    COHORT_YEAR_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ORGANIZATION_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ORGANIZATION_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_TYPE_ID INT UNIQUE NOT NULL,
    ORGANIZATION_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_EMPLOYMENT_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_EMPLOYMENT_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYMENT_TYPE_ID INT UNIQUE NOT NULL,
    EMPLOYMENT_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ORGANIZATION_OPERATIONAL_STATUS`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ORGANIZATION_OPERATIONAL_STATUS` (
    ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_OPERATIONAL_STATUS_ID INT UNIQUE NOT NULL,
    ORGANIZATION_OPERATIONAL_STATUS_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_PROGRAM_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_PROGRAM_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    PROGRAM_TYPE_ID INT UNIQUE NOT NULL,
    PROGRAM_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_IMMUNIZATION_TYPE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_IMMUNIZATION_TYPE` (
    ID INT NOT NULL AUTO_INCREMENT,
    IMMUNIZATION_TYPE_ID INT UNIQUE NOT NULL,
    IMMUNIZATION_TYPE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;  
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_INSURANCE_COVERAGE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_INSURANCE_COVERAGE` (
    ID INT NOT NULL AUTO_INCREMENT,
    INSURANCE_COVERAGE_ID INT UNIQUE NOT NULL,
    INSURANCE_COVERAGE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_DENTAL_TREATMENT_STATUS`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_DENTAL_TREATMENT_STATUS` (
    ID INT NOT NULL AUTO_INCREMENT,
    DENTAL_TREATMENT_STATUS_ID INT UNIQUE NOT NULL,
    DENTAL_TREATMENT_STATUS_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB; 
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_TRIMESTER_PRENATAL_CARE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_TRIMESTER_PRENATAL_CARE` (
    ID INT NOT NULL AUTO_INCREMENT,
    TRIMESTER_PRENATAL_CARE_ID INT UNIQUE NOT NULL,
    TRIMESTER_PRENATAL_CARE_DESCRIPTION VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB; 
   
DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ALLERGIES`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`LOOKUP_TABLE_ALLERGIES` (
    ID INT NOT NULL AUTO_INCREMENT,
    ALLERGY_CODE INT UNIQUE NOT NULL,
    ALLERGY_NAME VARCHAR(255) UNIQUE NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB; 

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`CHARACTERISTICS` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`CHARACTERISTICS` (
    ID INT NOT NULL AUTO_INCREMENT,
    BEGIN_DATE DATETIME,
    END_DATE DATETIME,
    DESIGNATED_BY VARCHAR(255),
    CHARACTERISTIC INT NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`CHARACTERISTICS` 
ADD CONSTRAINT characteristics_FK 
FOREIGN KEY (CHARACTERISTIC) REFERENCES LOOKUP_TABLE_STUDENT_CHARACTERISTICS(STUDENT_CHARACTERISTICS_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`COHORT_YEAR` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`COHORT_YEAR` (
    ID INT NOT NULL AUTO_INCREMENT,
    SCHOOL_YEARS INT NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`COHORT_YEAR` 
ADD CONSTRAINT cohort_year_FK 
FOREIGN KEY (SCHOOL_YEARS) REFERENCES LOOKUP_TABLE_COHORT_YEAR(COHORT_YEAR_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`ADDRESS` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`ADDRESS` (
    ID INT NOT NULL AUTO_INCREMENT,
    STREET_NUMBER VARCHAR(255),
    STREET_NAME VARCHAR(255) NOT NULL,
    APARTMENT_ROOM_SUITE_NUMBER VARCHAR(255),
    BUILDING_SITE_NUMBER VARCHAR(255),
    CITY VARCHAR(255) NOT NULL,
    STATE INT NOT NULL,
    POSTAL_CODE VARCHAR(50) NOT NULL,
    NAME_OF_COUNTRY VARCHAR(255),
    COUNTRY_FIPS_CODE VARCHAR(255),
    PROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    LATITUDE VARCHAR(255),
    LONGITUDE VARCHAR(255),
    BEGIN_DATE DATETIME,
    END_DATE DATETIME,
    IS_PRIMARY INT NOT NULL,
    DO_NOT_PUBLISH_INDICATOR INT NOT NULL,
    ADDRESS_TYPE INT,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`ADDRESS` 
ADD CONSTRAINT address_state_FK 
FOREIGN KEY (STATE) REFERENCES LOOKUP_TABLE_STATE(STATE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ADDRESS` 
ADD CONSTRAINT address_country_FK 
FOREIGN KEY (COUNTRY) REFERENCES LOOKUP_TABLE_COUNTRY(COUNTRY_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;


ALTER TABLE `CONTACT_INFO_MASTER`.`ADDRESS` ADD CONSTRAINT 
address_primary CHECK (IS_PRIMARY = 0 OR IS_PRIMARY = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`ADDRESS` ADD CONSTRAINT 
address_do_not_publish CHECK (DO_NOT_PUBLISH_INDICATOR = 0 OR DO_NOT_PUBLISH_INDICATOR = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`ADDRESS` 
ADD CONSTRAINT address_type_FK 
FOREIGN KEY (ADDRESS_TYPE) REFERENCES LOOKUP_TABLE_ADDRESS_TYPE(ADDRESS_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`PHONE` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`PHONE` (
    ID INT NOT NULL AUTO_INCREMENT,
    PHONE_TYPE_ID INT,
    PHONE_NUMBER VARCHAR(255) NOT NULL,
    ORDER_OF_PRIORITY INT NOT NULL,
    TEXT_MESSAGE_CAPABLE_INDICATOR INT,
    DO_NOT_PUBLISH_INDICATOR INT NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`PHONE` 
ADD CONSTRAINT phone_type_FK 
FOREIGN KEY (PHONE_TYPE_ID) REFERENCES LOOKUP_TABLE_PHONE_TYPE(PHONE_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PHONE` ADD CONSTRAINT 
text_message_capable CHECK (TEXT_MESSAGE_CAPABLE_INDICATOR = 0 OR TEXT_MESSAGE_CAPABLE_INDICATOR = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PHONE` ADD CONSTRAINT 
do_not_publish CHECK (DO_NOT_PUBLISH_INDICATOR = 0 OR DO_NOT_PUBLISH_INDICATOR = 1);

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`EMAIL` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`EMAIL` (
    ID INT NOT NULL AUTO_INCREMENT,
    ELECTRONIC_MAIL_TYPE_ID INT NOT NULL,
    ELECTRONIC_MAIL_ADDRESS VARCHAR(255) NOT NULL,
    PRIMARY_EMAIL_ADDRESS_INDICATOR INT NOT NULL,
    BOUNCE INT,
    DO_NOT_PUBLISH_INDICATOR INT,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`EMAIL` 
ADD CONSTRAINT email_type_FK 
FOREIGN KEY (ELECTRONIC_MAIL_TYPE_ID) REFERENCES LOOKUP_TABLE_EMAIL_TYPE(EMAIL_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`EMAIL` ADD CONSTRAINT 
email_bounce CHECK (BOUNCE = 0 OR BOUNCE = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`EMAIL` ADD CONSTRAINT 
primary_email_indicator CHECK (PRIMARY_EMAIL_ADDRESS_INDICATOR = 0 OR PRIMARY_EMAIL_ADDRESS_INDICATOR = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`EMAIL` ADD CONSTRAINT 
do_not_publish_email CHECK (DO_NOT_PUBLISH_INDICATOR = 0 OR DO_NOT_PUBLISH_INDICATOR = 1);

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`NAME` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`NAME` (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_SURNAME VARCHAR(255) NOT NULL,
    PERSONAL_TITLE_PREFIX VARCHAR(255),
    GENERATION_CODE_SUFFIX VARCHAR(255),
    MAIDEN_NAME VARCHAR(255),
    OTHER_NAME_TYPE INT,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`NAME` 
ADD CONSTRAINT other_name_type_FK 
FOREIGN KEY (OTHER_NAME_TYPE) REFERENCES LOOKUP_TABLE_OTHERNAME_TYPE(OTHERNAME_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`DISABILITY` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`DISABILITY` (
    ID INT NOT NULL AUTO_INCREMENT,
    SEVERITY INT NOT NULL,
    DIAGNOSIS VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
   DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`PROGRAM_PARTICIPATION` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`PROGRAM_PARTICIPATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    PROGRAM_ID INT,
    BEGIN_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    DESIGNATED_BY VARCHAR(255),
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`PROGRAM_PARTICIPATION` 
ADD CONSTRAINT program_id_FK 
FOREIGN KEY (PROGRAM_ID) REFERENCES program(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`PROGRAM` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`PROGRAM` (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PROGRAM_TYPE INT,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`PROGRAM` 
ADD CONSTRAINT program_type_FK 
FOREIGN KEY (PROGRAM_TYPE) REFERENCES LOOKUP_TABLE_PROGRAM_TYPE(PROGRAM_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`PERSON` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`PERSON` (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME_ID INT NOT NULL,
    OTHER_NAME_ID INT,
    SEX_TYPE INT NOT NULL,
    PHOTO_LOCATER_NUMBER VARCHAR(255),
    LANGUAGES INT,
    HOME_LNGUAGES INT,
    ADDRESS_ID INT NOT NULL,
    EMAIL_ID INT,
    PHONE_ID INT,
    BIRTHDATE DATE,
    HISPANIC_LATINO_IDENTITY INT,
    RACE INT,
    LOGIN_ID VARCHAR(255),
    UNIQUE_STATE_ID VARCHAR(255),
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` ADD CONSTRAINT 
latino_Identity CHECK (HISPANIC_LATINO_IDENTITY = 0 OR HISPANIC_LATINO_IDENTITY = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT race_FK 
FOREIGN KEY (RACE) REFERENCES LOOKUP_TABLE_RACE(RACE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT gender_FK 
FOREIGN KEY (SEX_TYPE) REFERENCES LOOKUP_TABLE_GENDER(GENDER_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT person_language_FK 
FOREIGN KEY (LANGUAGES) REFERENCES LOOKUP_TABLE_LANGUAGE_TYPE(LANGUAGE_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT person_home_language_FK 
FOREIGN KEY (HOME_LNGUAGES) REFERENCES LOOKUP_TABLE_LANGUAGE_TYPE(LANGUAGE_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT person_name_id_FK 
FOREIGN KEY (NAME_ID) REFERENCES name(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT person_other_name_id_FK 
FOREIGN KEY (OTHER_NAME_ID) REFERENCES name(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT address_id_FK 
FOREIGN KEY (ADDRESS_ID) REFERENCES address(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT email_id_FK 
FOREIGN KEY (EMAIL_ID) REFERENCES email(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PERSON` 
ADD CONSTRAINT phone_id_FK 
FOREIGN KEY (PHONE_ID) REFERENCES phone(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`STAFF` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`Staff` (
    ID INT NOT NULL AUTO_INCREMENT,
    PERSON_ID INT NOT NULL,
    CREATE_DATE DATETIME NOT NULL,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;


ALTER TABLE `CONTACT_INFO_MASTER`.`STAFF` 
ADD CONSTRAINT staff_person_id_FK 
FOREIGN KEY (PERSON_ID) REFERENCES person(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`PARENT` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`PARENT` (
    ID INT NOT NULL AUTO_INCREMENT,
    PERSON_ID INT NOT NULL,
    CREATE_DATE DATETIME NOT NULL,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT` 
ADD CONSTRAINT parent_person_id_FK 
FOREIGN KEY (PERSON_ID) REFERENCES person(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`STUDENT` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`STUDENT` (
    ID INT NOT NULL AUTO_INCREMENT,
    PERSON_ID INT NOT NULL,
    MULTIPLE_BIRTH_STATUS INT,
    ECONOMICALLY_DISADVANTAGED INT,
    SCHOOL_FOOD_ELIGIBLE INT,
    SCHOOL_FOOD_ELIGIBLE_DATE DATETIME,
    STATUS INT,
    STATUS_DESIGNATED_BY VARCHAR(255),
    VERIFIED_BY INT,
    CHARACTERISTICS_ID INT,
    LIMITED_ENGLISH_PROFICIENCY INT,
    DISABILITY INT,
    DISPLACEMENT_ID INT,
    PROGRAM_PARTICIPATION_ID INT,
    COHORT_YEAR_ID INT,
    INDICATOR VARCHAR(255),
    SYSTEM_TYPE_ID INT,
    PHOTO_SHARING INT,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_verified_by_FK 
FOREIGN KEY (VERIFIED_BY) REFERENCES LOOKUP_TABLE_PERSONAL_VERIFICATION_TYPE(PERSONAL_VERIFICATION_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_system_type_FK 
FOREIGN KEY (SYSTEM_TYPE_ID) REFERENCES LOOKUP_TABLE_STUDENT_ID_SYSTEM_TYPE(STUDENT_ID_SYSTEM_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_person_id_FK 
FOREIGN KEY (PERSON_ID) REFERENCES person(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_disability_id 
FOREIGN KEY (DISABILITY) REFERENCES DISABILITY(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_program_participation_id_FK 
FOREIGN KEY (PROGRAM_PARTICIPATION_ID) REFERENCES PROGRAM_PARTICIPATION(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_characteristic_id_FK 
FOREIGN KEY (CHARACTERISTICS_ID) REFERENCES Characteristics(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT` 
ADD CONSTRAINT student_cohort_year_FK 
FOREIGN KEY (COHORT_YEAR_ID) REFERENCES COHORT_YEAR(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`ORGANIZATION` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`ORGANIZATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME_OF_INSTITUTION VARCHAR(255) NOT NULL,
    SHORT_NAME_OF_INSTITUTION VARCHAR(255),
    ORGANIZATION_TYPE INT,
    ADDRESS_ID INT NOT NULL,
    EMAIL_ID INT,
    PHONE_ID INT,
    WEBSITE VARCHAR(255),
    STATE_ID VARCHAR(255),
    OPERATIONAL_STATUS INT,
    PROGRAM_ID INT,
    PARENT_ORG_ID INT,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`ORGANIZATION` 
ADD CONSTRAINT organization_type_FK 
FOREIGN KEY (ORGANIZATION_TYPE) REFERENCES LOOKUP_TABLE_ORGANIZATION_TYPE(ORGANIZATION_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ORGANIZATION` 
ADD CONSTRAINT operational_status_FK 
FOREIGN KEY (OPERATIONAL_STATUS) REFERENCES LOOKUP_TABLE_ORGANIZATION_OPERATIONAL_STATUS(ORGANIZATION_OPERATIONAL_STATUS_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ORGANIZATION` 
ADD CONSTRAINT org_program_id_FK 
FOREIGN KEY (PROGRAM_ID) REFERENCES program(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ORGANIZATION` 
ADD CONSTRAINT org_address_id_FK 
FOREIGN KEY (ADDRESS_ID) REFERENCES address(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ORGANIZATION` 
ADD CONSTRAINT org_email_id_FK 
FOREIGN KEY (EMAIL_ID) REFERENCES email(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ORGANIZATION` 
ADD CONSTRAINT org_phone_id_FK 
FOREIGN KEY (PHONE_ID) REFERENCES phone(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` ;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    PARENT_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    RELATIONSHIP_TYPE INT NOT NULL,
    PRIMARY_CONTACT_STATUS INT,
    LIVES_WITH INT,
    CONTACT_PRIORITY INT,
    CONTACT_RESTRICTION INT,
    PICKUP_APPROVED INT,
    EMERGENCY_CONTACT_STATUS INT,
    CREATE_DATE DATETIME NOT NULL,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` ADD CONSTRAINT 
primary_contact_status CHECK (PRIMARY_CONTACT_STATUS = 0 OR PRIMARY_CONTACT_STATUS = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` ADD CONSTRAINT 
lives_with CHECK (LIVES_WITH = 0 OR LIVES_WITH = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` ADD CONSTRAINT 
contact_restriction CHECK (CONTACT_RESTRICTION = 0 OR CONTACT_RESTRICTION = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` ADD CONSTRAINT 
pickup_approved CHECK (PICKUP_APPROVED = 0 OR PICKUP_APPROVED = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` ADD CONSTRAINT 
emergency_contact_status CHECK (EMERGENCY_CONTACT_STATUS = 0 OR EMERGENCY_CONTACT_STATUS = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` 
ADD CONSTRAINT relation_type_FK 
FOREIGN KEY (RELATIONSHIP_TYPE) REFERENCES LOOKUP_TABLE_RELATION(RELATION_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` 
ADD CONSTRAINT parent_student_assoc_parent_id_FK 
FOREIGN KEY (PARENT_ID) REFERENCES parent(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`PARENT_STUDENT_ASSOCIATION` 
ADD CONSTRAINT parent_student_assoc_student_id_FK 
FOREIGN KEY (STUDENT_ID) REFERENCES student(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`STUDENT_ORG_ASSOCIATION`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`STUDENT_ORG_ASSOCIATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    ENTRY_DATE DATETIME NOT NULL,
    CREATE_DATE DATETIME NOT NULL,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT_ORG_ASSOCIATION` 
ADD CONSTRAINT student_org_organization_id_FK 
FOREIGN KEY (ORGANIZATION_ID) REFERENCES Organization(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STUDENT_ORG_ASSOCIATION` 
ADD CONSTRAINT student_org_student_id_FK 
FOREIGN KEY (STUDENT_ID) REFERENCES student(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`STAFF_ORG_ASSOCIATION`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`STAFF_ORG_ASSOCIATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,
    STAFF_CLASSIFICATION_DESCRIPTOR_ID INT NOT NULL,
    POSITION_TITLE VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(255),
    EMPLOYMENT_STATUS INT,
    OFFER_DATE DATETIME,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`STAFF_ORG_ASSOCIATION` 
ADD CONSTRAINT staff_classification_FK 
FOREIGN KEY (STAFF_CLASSIFICATION_DESCRIPTOR_ID) REFERENCES LOOKUP_TABLE_DISTRICT_USER_CLASSIFICATION(USER_CLASSIFICATION_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STAFF_ORG_ASSOCIATION` 
ADD CONSTRAINT employment_status_FK 
FOREIGN KEY (EMPLOYMENT_STATUS) REFERENCES LOOKUP_TABLE_EMPLOYMENT_TYPE(EMPLOYMENT_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STAFF_ORG_ASSOCIATION` 
ADD CONSTRAINT staff_org_organization_id_FK 
FOREIGN KEY (ORGANIZATION_ID) REFERENCES Organization(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`STAFF_ORG_ASSOCIATION` 
ADD CONSTRAINT staff_org_staff_id_FK 
FOREIGN KEY (STAFF_ID) REFERENCES staff(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`HEALTH`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`HEALTH` (
    ID INT NOT NULL AUTO_INCREMENT,
    MEDICAL_ALERT_INDICATOR INT NOT NULL,
    SCREENING_EQUIPMENT_USED VARCHAR(255),
    SCREENING_FOLLOW_UP_RECOMMENDED INT,
    DENTAL_SCREENING_STATUS INT,
    TRIMESTER_FOR_PRENATAL_CARE INT,
    DOCTOR_NAME VARCHAR(255),
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`HEALTH` 
ADD CONSTRAINT dental_screening_status_FK 
FOREIGN KEY (DENTAL_SCREENING_STATUS) REFERENCES LOOKUP_TABLE_DENTAL_TREATMENT_STATUS(DENTAL_TREATMENT_STATUS_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`HEALTH` 
ADD CONSTRAINT trimester_prenatal_care_FK 
FOREIGN KEY (TRIMESTER_FOR_PRENATAL_CARE) REFERENCES LOOKUP_TABLE_TRIMESTER_PRENATAL_CARE(TRIMESTER_PRENATAL_CARE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`ALLERGY`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`ALLERGY` (
    ID INT NOT NULL AUTO_INCREMENT,
    HEALTH_ID INT NOT NULL,
    ALLERGY_CODE INT NOT NULL,
    REACTION_DESCRIPTION VARCHAR(255),
    SEVERITY INT,
    ALLERGY_NAME VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`ALLERGY` 
ADD CONSTRAINT allergy_health_id_FK 
FOREIGN KEY (HEALTH_ID) REFERENCES health(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ALLERGY` ADD CONSTRAINT 
severity CHECK (SEVERITY = 0 OR SEVERITY = 1);

ALTER TABLE `CONTACT_INFO_MASTER`.`ALLERGY` 
ADD CONSTRAINT allergy_code_FK 
FOREIGN KEY (ALLERGY_CODE) REFERENCES LOOKUP_TABLE_ALLERGIES(ALLERGY_CODE)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`ALLERGY` 
ADD CONSTRAINT allergy_name_FK 
FOREIGN KEY (ALLERGY_NAME) REFERENCES LOOKUP_TABLE_ALLERGIES(ALLERGY_NAME)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`HEALTH_INSURANCE`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`HEALTH_INSURANCE` (
    ID INT NOT NULL AUTO_INCREMENT,
    HEALTH_ID INT NOT NULL,
    INSURANCE_TYPE INT NOT NULL,
    START_DATE DATETIME,
    END_DATE DATETIME,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;

ALTER TABLE `CONTACT_INFO_MASTER`.`HEALTH_INSURANCE` 
ADD CONSTRAINT health_insurance_health_id_FK 
FOREIGN KEY (HEALTH_ID) REFERENCES health(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;


ALTER TABLE `CONTACT_INFO_MASTER`.`HEALTH_INSURANCE` 
ADD CONSTRAINT insurance_type_FK 
FOREIGN KEY (INSURANCE_TYPE) REFERENCES LOOKUP_TABLE_INSURANCE_COVERAGE(INSURANCE_COVERAGE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

DROP TABLE IF EXISTS `CONTACT_INFO_MASTER`.`IMMUNIZATION`;

CREATE TABLE IF NOT EXISTS `CONTACT_INFO_MASTER`.`IMMUNIZATION` (
    ID INT NOT NULL AUTO_INCREMENT,
    HEALTH_ID INT NOT NULL,
    IMMUNIZATION_DATE DATETIME NOT NULL,
    IMMUNIZATION_TYPE INT NOT NULL,
    CREATE_DATE DATETIME,
    LAST_MODIFIED_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
)  ENGINE=InnoDB;
   
ALTER TABLE `CONTACT_INFO_MASTER`.`IMMUNIZATION` 
ADD CONSTRAINT immunization_health_id_FK 
FOREIGN KEY (HEALTH_ID) REFERENCES health(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE `CONTACT_INFO_MASTER`.`IMMUNIZATION` 
ADD CONSTRAINT immunization_type_FK 
FOREIGN KEY (IMMUNIZATION_TYPE) REFERENCES LOOKUP_TABLE_IMMUNIZATION_TYPE(IMMUNIZATION_TYPE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

   
SET foreign_key_checks = 1;